# Generated by Django 5.2.4 on 2025-07-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aprendiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento_identidad", models.CharField(max_length=15)),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("telefono", models.CharField(max_length=12)),
                ("correo", models.EmailField(max_length=50)),
                ("fecha_nacimiento", models.DateField()),
                ("ciudad", models.CharField(max_length=50)),
                ("programa", models.CharField(max_length=100)),
            ],
        ),
    ]
