# Generated by Django 5.2.4 on 2025-08-07 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_alter_aprendiz_options_aprendizcurso_curso_and_more'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprendizcurso',
            options={'verbose_name': 'Aprendiz por Curso', 'verbose_name_plural': 'Aprendices por Curso'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='instructorcurso',
            options={'verbose_name': 'Instructor por Curso', 'verbose_name_plural': 'Instructores por Curso'},
        ),
        migrations.RemoveField(
            model_name='aprendiz',
            name='programa',
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='documento_identidad',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aprendizcurso',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=30, unique=True, verbose_name='Código del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cupos_maximos',
            field=models.PositiveIntegerField(verbose_name='Cupos Máximos'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('PRO', 'Programado'), ('INI', 'Iniciado'), ('EJE', 'En Ejecución'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado'), ('SUS', 'Suspendido')], default='PRO', max_length=3, verbose_name='Estado del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa', verbose_name='Programa de Formación'),
        ),
        migrations.AlterField(
            model_name='instructorcurso',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación'),
        ),
    ]
