# Generated by Django 5.2.4 on 2025-07-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cedula de Ciudadania"),
                            ("CE", "Cedula de Extranjeria"),
                            ("TI", "Tarjeta de Identidad"),
                            ("PA", "Pasaporte"),
                        ],
                        default="CC",
                        max_length=3,
                    ),
                ),
                ("documento_identidad", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=10)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("fecha_nacimiento", models.DateField()),
                ("ciudad", models.CharField(max_length=100, null=True)),
                ("direccion", models.CharField(max_length=100, null=True)),
                (
                    "nivel_educativo",
                    models.CharField(
                        choices=[
                            ("TEC", "Tecnico"),
                            ("TGL", "Tegnologo"),
                            ("PRE", "Pregrado"),
                            ("ESP", "Especializacion"),
                            ("MAE", "Maestria"),
                            ("DOC", "Doctorado"),
                        ],
                        default="MAE",
                        max_length=3,
                    ),
                ),
                ("especialidad", models.CharField(max_length=100)),
                ("anios_experiencia", models.PositiveIntegerField()),
                ("activo", models.BooleanField(default=True)),
                ("fecha_vinculacion", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
